# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.mikemedis.tech" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Michael Medis # Your name will go here
  description: "Software Developer" # used by search engines

  # Header and footer text
  header_text: >
     <h1>I'm Mike.</h1>
     <p>a software developer.</p>
  header_text_feature_image:
  footer_text: >
   Powered by Obsession and Desire to know everything Software.

  # Icons
  rss: false
  email_address: "mike@mikemedis.tech" # Full email address, e.g. "sam@example.com"
  facebook: "https://www.facebook.com/michael.medis"
  github: "mikeMedis" # github profile name, e.g. "madebymunsters"
  linkedin: "www.linkedin.com/in/michael-medis-32256"

  # Scripts
  google_analytics: "UA-79655907-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Shadows Into Light:300,400,700,300italic,700italic|Abril+Fatface"

# PAGINATION
paginate: 100
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# BUILD SETTINGS
markdown: kramdown

highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
