# SITE CONFIGURATION
baseurl: "/portfolio-kami" # the subpath of your site, e.g. /blog/
url: "http://www.domain.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Michael Medis # Your name will go here
  description: "Michael Medis | Web Developer" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Michael is a Passionate Rails & Javascript Developer</h1>
     <p>I'm a kickass developer specializing in Rails, AngularJS, and MongoDB.</p>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> and made with love.

  # Icons
  rss: false
  email_address: "medis.michael@gmail.com" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble: "https://dribbble.com/therealmedis"
  facebook: "https://www.facebook.com/michael.medis"
  flickr:
  github: "mikeMedis" # github profile name, e.g. "madebymunsters"
  google_plus:
  instagram:
  linkedin: "https://www.linkedin.com/in/michael-medis-32b467111?authType=NAME_SEARCH&authToken=JnI0&locale=en_US&srchid=4699317951463957159077&srchindex=1&srchtotal=26&trk=vsrp_people_res_photo&trkInfo=VSRPsearchId%3A4699317951463957159077%2CVSRPtargetId%3A469931795%2CVSRPcmpt%3Aprimary%2CVSRPnm%3Atrue%2CauthType%3ANAME_SEARCH" # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  "http://stackexchange.com/users/8493338/michael-medis" # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Lato:300,400,700,300italic,700italic|Abril+Fatface"

# PAGINATION
paginate: 100
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# BUILD SETTINGS
markdown: kramdown

highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
